<?php

namespace App\Actions\Blueprint;

use App\Models\Epic;
use App\Models\Project;
use App\Support\BlueprintKeyFactory;

class SyncEpicsAction
{
    /**
     * Persist epics and user stories generated by AI.
     *
     * @param array<int, array<string, mixed>> $epics
     */
    public function __invoke(Project $project, array $epics, string $promptHash): void
    {
        $existingEpics = $project->epics()
            ->where('is_ai_generated', true)
            ->with(['userStories' => function ($query) {
                $query->where('is_ai_generated', true)->orderBy('position');
            }])
            ->get()
            ->keyBy(fn (Epic $epic) => BlueprintKeyFactory::epic($epic->title));

        $retainedEpicIds = [];
        $epicPosition = 100;

        foreach ($epics as $epicData) {
            $epicKey = BlueprintKeyFactory::epic($epicData['title']);

            /** @var \App\Models\Epic $epic */
            $epic = $existingEpics[$epicKey] ?? $project->epics()->make();

            $epic->fill([
                'title' => $epicData['title'],
                'position' => $epicPosition,
                'is_ai_generated' => true,
                'origin_prompt_hash' => $promptHash,
            ]);
            $epic->save();

            $retainedEpicIds[] = $epic->id;
            $epicPosition += 100;

            $existingStories = $epic->userStories()
                ->where('is_ai_generated', true)
                ->get()
                ->keyBy(fn ($story) => BlueprintKeyFactory::story($story->content));

            $retainedStoryIds = [];
            $storyPosition = 100;
            foreach ($epicData['stories'] as $storyData) {
                $storyKey = BlueprintKeyFactory::story($storyData['content']);
                $story = $existingStories[$storyKey] ?? $epic->userStories()->make();

                $story->fill([
                    'content' => $storyData['content'],
                    'original_content' => $storyData['content'],
                    'priority' => $storyData['priority'] ?? ($story->priority ?? 'medium'),
                    'position' => $storyPosition,
                    'is_ai_generated' => true,
                    'origin_prompt_hash' => $promptHash,
                ]);
                $story->save();

                $retainedStoryIds[] = $story->id;
                $storyPosition += 100;
            }

            $epic->userStories()
                ->where('is_ai_generated', true)
                ->whereNotIn('id', $retainedStoryIds)
                ->delete();
        }

        $project->epics()
            ->where('is_ai_generated', true)
            ->whereNotIn('id', $retainedEpicIds)
            ->delete();
    }
}
